import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

export const darkMapStyle = [
  { "elementType": "geometry", "stylers": [{ "color": "#1d2c4d" }] },
  { "elementType": "labels.text.fill", "stylers": [{ "color": "#8ec3b9" }] },
  { "elementType": "labels.text.stroke", "stylers": [{ "color": "#1a3646" }] },
  { "featureType": "administrative.country", "elementType": "geometry.stroke", "stylers": [{ "color": "#4b6878" }] },
  { "featureType": "landscape.man_made", "elementType": "geometry.stroke", "stylers": [{ "color": "#334e87" }] },
  { "featureType": "landscape.natural", "elementType": "geometry", "stylers": [{ "color": "#023e58" }] },
  { "featureType": "poi", "elementType": "geometry", "stylers": [{ "color": "#283d6a" }] },
  { "featureType": "poi", "elementType": "labels.text.fill", "stylers": [{ "color": "#6f9ba5" }] },
  { "featureType": "road", "elementType": "geometry", "stylers": [{ "color": "#304a7d" }] },
  { "featureType": "road", "elementType": "labels.text.fill", "stylers": [{ "color": "#98a5be" }] },
  { "featureType": "road.highway", "elementType": "geometry", "stylers": [{ "color": "#2c6675" }] },
  { "featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{ "color": "#255763" }] },
  { "featureType": "water", "elementType": "geometry", "stylers": [{ "color": "#0e1626" }] },
  { "featureType": "water", "elementType": "labels.text.fill", "stylers": [{ "color": "#4e6d70" }] }
];

const styles = StyleSheet.create({
  container: { flex: 1 },
  map: { width: width, height: height },
  userDot: { width: 18, height: 18, borderRadius: 9, borderWidth: 3, borderColor: 'white', elevation: 5 },
  searchContainer: { position: 'absolute', zIndex: 10, width: '100%', alignItems: 'center', paddingHorizontal: 20 },
  searchBar: { flexDirection: 'row', alignItems: 'center', width: '100%', height: 70, borderRadius: 20, paddingHorizontal: 15, borderWidth: 1 },
  searchInput: { flex: 1, fontSize: 16, fontWeight: '500' },
  searchCardContainer: { position: 'absolute', bottom: 30, width: '100%', paddingHorizontal: 20, zIndex: 10 },
  searchResultCard: { padding: 15, borderRadius: 25, borderWidth: 1, marginBottom: 60 },
  searchResultImg: { width: '100%', height: 175, borderRadius: 12 },
  searchResultTitle: { fontSize: 18, fontWeight: 'bold' },
  searchCardButtons: { flexDirection: 'row', marginTop: 15, justifyContent: 'space-between' },
  actionBtn: { flex: 0.31, flexDirection: 'row', height: 45, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  actionBtnText: { color: '#fff', fontWeight: 'bold', marginLeft: 8 },
  pinWrapper: { alignItems: 'center' },
  pinCircle: { width: 34, height: 34, borderRadius: 17, borderWidth: 3, overflow: 'hidden', justifyContent: 'center', alignItems: 'center', elevation: 5 },
  markerImage: { width: '100%', height: '100%' },
  pinTail: { width: 0, height: 0, borderLeftWidth: 6, borderRightWidth: 6, borderTopWidth: 8, borderLeftColor: 'transparent', borderRightColor: 'transparent', marginTop: -1 },
  closeStreetView: { position: 'absolute', right: 20, zIndex: 999 },
  viewerOverlay: { flex: 1, backgroundColor: '#000' },
  viewerHeader: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 50, zIndex: 100, position: 'absolute', top: 0, width: '100%' },
  headerCircleBtn: { backgroundColor: 'rgba(0,0,0,0.5)', width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' },
  mediaSlide: { width: width, height: height, justifyContent: 'center' },
  fullMedia: { width: width, height: '100%' },
  viewerSingleDelete: { position: 'absolute', top: 135, right: 10, padding: 10, borderRadius: 15, flexDirection: 'row', alignItems: 'center' },
  deleteBtnText: { color: 'white', marginLeft: 5, fontWeight: '600', fontSize: 12 },
  paginationRow: { flexDirection: 'row', justifyContent: 'center', position: 'absolute', bottom: 210, width: '100%' },
  dot: { width: 8, height: 8, borderRadius: 4, marginHorizontal: 5 },
  enhancedDetails: { marginHorizontal: 20, padding: 25, borderRadius: 25, position: 'absolute', bottom: 40, width: width - 40 },
  viewerTitle: { fontSize: 26, fontWeight: 'bold', marginBottom: 8 },
  viewerDescription: { fontSize: 16, lineHeight: 22 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { width: '90%', padding: 25, borderRadius: 30, borderWidth: 1 },
  modalHeader: { fontSize: 22, fontWeight: '800', marginBottom: 15 },
  mediaSection: { height: 90, marginBottom: 15 },
  addMediaBtn: { width: 80, height: 80, borderRadius: 20, borderStyle: 'dashed', borderWidth: 2, justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  previewContainer: { width: 80, height: 80, borderRadius: 20, marginRight: 15 },
  previewItem: { width: '100%', height: '100%', borderRadius: 20 },
  removeBadge: { position: 'absolute', top: -5, right: -5, zIndex: 10 },
  input: { width: '100%', borderRadius: 15, padding: 15, marginBottom: 12, borderWidth: 1 },
  buttonRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 },
  btnSave: { paddingHorizontal: 25, paddingVertical: 12, borderRadius: 15 },
  modalCloseIcon: { position: 'absolute', top: 25, right: 25, zIndex: 10 },
  btnSaveText: { color: '#fff', fontWeight: 'bold' },
  cancelNavBtn: { position: 'absolute', right: 20, zIndex: 20 },
  cancelNavCard: { flexDirection: 'row', alignItems: 'center', padding: 10, borderRadius: 15, backgroundColor: 'rgba(0,0,0,0.6)' },
  shareFab: { position: 'absolute', left: 20, width: 52, height: 52, borderRadius: 26, justifyContent: 'center', alignItems: 'center', zIndex: 11, elevation: 6, shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 4 },
  liveMarker: { width: 30, height: 30, borderRadius: 25, borderWidth: 3, borderColor: '#10B981', overflow: 'hidden', backgroundColor: '#fff' },  
  liveAvatar: { width: '100%', height: '100%', borderRadius: 25 }, // Apply borderRadius directly to the Image
  liveMarkerContainer: { alignItems: 'center', justifyContent: 'center' },
  userListContainer: { height: 350, marginVertical: 15 },
  userItem: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 15, marginBottom: 8, borderWidth: 1 },
  userAvatar: { width: 40, height: 40, borderRadius: 20, marginRight: 12 },
  userSelectBadge: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, justifyContent: 'center', alignItems: 'center' },
  modalSearchInput: { height: 50, borderRadius: 15, paddingHorizontal: 15, marginBottom: 10, borderWidth: 1 },
  
  // New styles for travel mode and estimated time
  travelModeContainer: { position: 'absolute', width: '100%', alignItems: 'center', zIndex: 10, paddingHorizontal: 20, paddingBottom: 80 },
  travelModeCard: { padding: 10, borderRadius: 25, borderWidth: 1, flexDirection: 'column', alignItems: 'center' },
  travelModeButtons: { flexDirection: 'row', justifyContent: 'space-around', width: '100%', marginBottom: 10 },
  travelModeButton: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6, paddingHorizontal: 8, borderRadius: 20, marginHorizontal: 2 },
  travelModeButtonText: { marginLeft: 4, fontWeight: '600', fontSize: 12 },
  estimatedTimeText: { fontSize: 16, fontWeight: '700', textAlign: 'center', marginBottom: 5 },

  shareModalFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 }, // Existing, ensure no conflict
  shareSubmitBtn: { flex: 1, height: 50, borderRadius: 15, justifyContent: 'center', alignItems: 'center', marginLeft: 10 }, // Existing, ensure no conflict
  shareCancelBtn: { flex: 0.4, height: 50, justifyContent: 'center', alignItems: 'center' }, // Existing, ensure no conflict
  stampingOverlay: {
    position: 'absolute',
    left: 20,
    right: 20,
    zIndex: 1000,
    borderRadius: 22,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
});

export default styles;