// src/constants/assets.js

export const EMOTION_ASSETS = {
  Burnout: require('../assets/burnout.json'),
  Calm: require('../assets/chill.json'),
  Fire: require('../assets/Fire.json'),
  Play: require('../assets/play.json'),
  Loved: require('../assets/inlove.json'),
  Sad: require('../assets/sad.json'),
  Sick: require('../assets/sick.json'),
  Walk: require('../assets/walk.json'),
  ChillBeach: require('../assets/Watermelon.json'),
  NoEnergy: require('../assets/saddog.json'),
  Jogging: require('../assets/runcycle.json'),
  Ok: require('../assets/okdog.json'),
  Rides: require('../assets/RIder.json'),
  Haha: require('../assets/haha.json'),
  What: require('../assets/dogshock.json'),
  Blee: require('../assets/bledog.json'),
  Beach: require('../assets/Beach.json'),
  Sneaking: require('../assets/amongus.json'),
  Crying: require('../assets/Cryingemoji.json'),
  Drunk: require('../assets/drunkbeer.json'),
  Thinking: require('../assets/Thinking.json'),
  Skating: require('../assets/Orangeskating.json'),
  Walking: require('../assets/WalkingOrange.json'),
  // New Assets from Screenshot
  Dragonflying: require('../assets/Dragonflying.json'),
  WaveyBirdie: require('../assets/WaveyBirdie.json'),
  Dogparty: require('../assets/dogparty.json'),
  Groovywalk: require('../assets/Groovywalk.json'),
  TotoroWalk: require('../assets/TotoroWalk.json'),
  MoodyDog: require('../assets/MoodyDog.json'),
  Hrundel: require('../assets/Hrundel.json'),
  Fatherday: require('../assets/Fatherday.json'),
  AvocadoFruit: require('../assets/AvocadoFruit.json'),
  Handwave: require('../assets/handwave.json'),
  ClappingHands: require('../assets/ClappingHands.json'),
  Snake: require('../assets/Snake.json'),
  Book: require('../assets/Book.json'),
  EmojiMoney: require('../assets/emojimoney.json'),
  FlyingMoney: require('../assets/flyingmoney.json'),
  AngryEmoji: require('../assets/Angryemoji.json'),
  CatMarkLoading: require('../assets/catMarkloading.json'),
  CatInBox: require('../assets/CatinBox.json'),
};

export const EMOTION_CONFIG = [
  { label: 'Burnout', value: 'Burnout', assetKey: 'Burnout' },
  { label: 'Chill', value: 'Calm', assetKey: 'Calm' },
  { label: 'Fire', value: 'Fire', assetKey: 'Fire' },
  { label: 'Play', value: 'Play', assetKey: 'Play' },
  { label: 'In Love', value: 'In Love', assetKey: 'Loved' },
  { label: 'Sad', value: 'Sad', assetKey: 'Sad' },
  { label: 'Sick', value: 'Sick', assetKey: 'Sick' },
  { label: 'Walk', value: 'Walk', assetKey: 'Walk' },
  { label: 'Chill Beach', value: 'Chill Beach', assetKey: 'ChillBeach' },
  { label: 'No Energy', value: 'No Energy', assetKey: 'NoEnergy' },
  { label: 'Jogging', value: 'Jogging', assetKey: 'Jogging' },
  { label: 'Ok', value: 'Ok', assetKey: 'Ok' },
  { label: 'Rides', value: 'Rides', assetKey: 'Rides' },
  { label: 'Haha', value: 'haha', assetKey: 'Haha' },
  { label: 'What', value: 'What', assetKey: 'What' },
  { label: 'Blee', value: 'Blee', assetKey: 'Blee' },
  { label: 'Beach', value: 'Beach', assetKey: 'Beach' },
  { label: 'Sneaking', value: 'Sneaking', assetKey: 'Sneaking' },
  { label: 'Crying', value: 'Crying', assetKey: 'Crying' },
  { label: 'Drunk', value: 'Drunk', assetKey: 'Drunk' },
  { label: 'Thinking', value: 'Thinking', assetKey: 'Thinking' },
  { label: 'Skating', value: 'Skating', assetKey: 'Skating' },
  { label: 'Walking', value: 'Walking', assetKey: 'Walking' },
  // New Configs
  { label: 'Dragon', value: 'Dragonflying', assetKey: 'Dragonflying' },
  { label: 'Birdie', value: 'WaveyBirdie', assetKey: 'WaveyBirdie' },
  { label: 'Dog Party', value: 'Dogparty', assetKey: 'Dogparty' },
  { label: 'Groovy Walk', value: 'Groovywalk', assetKey: 'Groovywalk' },
  { label: 'Totoro Walk', value: 'TotoroWalk', assetKey: 'TotoroWalk' },
  { label: 'Moody Dog', value: 'MoodyDog', assetKey: 'MoodyDog' },
  { label: 'Hrundel', value: 'Hrundel', assetKey: 'Hrundel' },
  { label: 'Father Day', value: 'Fatherday', assetKey: 'Fatherday' },
  { label: 'Avocado', value: 'AvocadoFruit', assetKey: 'AvocadoFruit' },
  { label: 'Hand Wave', value: 'Handwave', assetKey: 'Handwave' },
  { label: 'Clapping', value: 'ClappingHands', assetKey: 'ClappingHands' },
  { label: 'Snake', value: 'Snake', assetKey: 'Snake' },
  { label: 'Reading', value: 'Book', assetKey: 'Book' },
  { label: 'Money Emoji', value: 'EmojiMoney', assetKey: 'EmojiMoney' },
  { label: 'Flying Money', value: 'FlyingMoney', assetKey: 'FlyingMoney' },
  { label: 'Angry', value: 'AngryEmoji', assetKey: 'AngryEmoji' },
  { label: 'Cat Loading', value: 'CatMarkLoading', assetKey: 'CatMarkLoading' },
  { label: 'Cat in Box', value: 'CatInBox', assetKey: 'CatInBox' },
];