/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 frontend/assets/NormalCar2.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Model(props) {
  const { nodes, materials } = useGLTF(require('./NormalCar2.glb'))
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.162}>
        <mesh geometry={nodes.NormalCar2_BackWheels_Cylinder003_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.NormalCar2_BackWheels_Cylinder003_2.geometry} material={materials.Grey} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.162}>
        <mesh geometry={nodes.NormalCar2_Cube002_1.geometry} material={materials.LightBlue} />
        <mesh geometry={nodes.NormalCar2_Cube002_2.geometry} material={materials.Windows} />
        <mesh geometry={nodes.NormalCar2_Cube002_3.geometry} material={materials.Black} />
        <mesh geometry={nodes.NormalCar2_Cube002_4.geometry} material={materials.Grey} />
        <mesh geometry={nodes.NormalCar2_Cube002_5.geometry} material={materials.Headlights} />
        <mesh geometry={nodes.NormalCar2_Cube002_6.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.NormalCar2_Cube002_7.geometry} material={materials.TailLights} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.162}>
        <mesh geometry={nodes.NormalCar2_FrontLeftWheel_Cylinder015_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.NormalCar2_FrontLeftWheel_Cylinder015_2.geometry} material={materials.Grey} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.162}>
        <mesh geometry={nodes.NormalCar2_FrontRightWheel_Cylinder016_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.NormalCar2_FrontRightWheel_Cylinder016_2.geometry} material={materials.Grey} />
      </group>
    </group>
  )
}

useGLTF.preload(require('./NormalCar2.glb'))
