import { Dimensions, StyleSheet } from 'react-native';
export const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    headerArea: { paddingHorizontal: 20, paddingTop: 15, paddingBottom: 5 },
    categoryScroll: { paddingRight: 20, marginBottom: 10, height: 50 },
    categoryPill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 25, marginRight: 10, borderWidth: 1, height: 40 },
    categoryLabel: { marginLeft: 6, fontSize: 13, fontWeight: '800' },
    scrollContent: { paddingHorizontal: 20, paddingBottom: 100 },
    searchWrapper: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, height: 50, borderRadius: 15, borderWidth: 1, marginBottom: 15, gap: 10 },
    searchInput: { flex: 1, marginLeft: 10, fontSize: 15 },
    radiusBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, borderWidth: 1, gap: 5 },
    radiusBtnText: { fontSize: 12, fontWeight: '600' },
    mapContainer: { width: '100%', height: 250, borderRadius: 30, overflow: 'hidden', marginBottom: 20, borderWidth: 1 },
    map: { width: '100%', height: '100%' },
    customMarker: { padding: 6, borderRadius: 12, borderWidth: 2, borderColor: 'white', elevation: 5 },
    recenterBtn: { position: 'absolute', bottom: 15, right: 15, padding: 10, borderRadius: 12, elevation: 5 },
    resultsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15, paddingHorizontal: 5 },
    sectionTitle: { fontSize: 20, fontWeight: '900' },
    placeCard: { flexDirection: 'row', alignItems: 'center', padding: 10, borderRadius: 22, borderWidth: 1, marginBottom: 12 },
    imgContainer: { width: 75, height: 75, borderRadius: 18, overflow: 'hidden' },
    placeImg: { width: '100%', height: '100%' },
    ratingBadge: { position: 'absolute', top: 5, left: 5, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8 },
    ratingText: { color: 'white', fontSize: 10, fontWeight: '900' },
    placeInfo: { flex: 1, marginLeft: 15 },
    placeName: { fontWeight: '900', fontSize: 16, marginBottom: 4 },
    addressRow: { flexDirection: 'row', alignItems: 'center' },
    placeAddress: { fontSize: 12, opacity: 0.7 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'flex-end' },
    modalContent: { height: height * 0.75, borderTopLeftRadius: 35, borderTopRightRadius: 35, padding: 25, alignItems: 'center' },
    modalHandle: { width: 40, height: 4, backgroundColor: '#444', borderRadius: 2, marginBottom: 20 },
    modalHeroContainer: { width: '100%', height: 280, borderRadius: 25, overflow: 'hidden', marginBottom: 20, position: 'relative' },
    modalHeroImg: { width: '100%', height: '100%' },
    modalBookmarkBtn: { position: 'absolute', top: 15, right: 15, backgroundColor: 'rgba(0,0,0,0.3)', padding: 10, borderRadius: 15 },
    modalTitle: { fontSize: 24, fontWeight: '900', textAlign: 'center' },
    modalSub: { fontSize: 14, textAlign: 'center', marginTop: 8, marginBottom: 30 },
    actionBtn: { width: '100%', height: 60, borderRadius: 20, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
    actionBtnText: { color: 'white', fontWeight: '900', fontSize: 17 },
    closeBtnTop: { position: 'absolute', top: 5, right: 10, zIndex: 10, padding: 8, borderRadius: 20 },
    radiusModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
    radiusModalContent: { width: '85%', borderRadius: 20, padding: 20, borderWidth: 1, elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 3.84 },
    radiusModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    radiusModalTitle: { fontSize: 18, fontWeight: '700' },
    radiusOption: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 10, borderRadius: 10, marginBottom: 8 },
    radiusOptionLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    radiusOptionLabel: { fontSize: 15, fontWeight: '500' },
    radiusOptionValue: { fontSize: 13, fontWeight: '600' },
    distanceBadge: { position: 'absolute', bottom: 5, right: 5, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10, backgroundColor: 'rgba(0,0,0,0.6)' },
    distanceText: { color: 'white', fontSize: 10, fontWeight: '600' },
    quickAccessContainer: { marginBottom: 15 },
quickAccessTitle: { fontSize: 14, fontWeight: '600', marginBottom: 10, marginLeft: 5 },
quickAccessScroll: { paddingRight: 20 },
quickAccessItem: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 25, marginRight: 10, borderWidth: 1, gap: 8 },
quickAccessLabel: { fontSize: 14, fontWeight: '600' },
categoryGroupScroll: { paddingRight: 20, marginBottom: 10 },
categoryGroupPill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, paddingVertical: 12, borderRadius: 30, marginRight: 12, borderWidth: 1, gap: 8 },
categoryGroupLabel: { fontSize: 14, fontWeight: '600' },
categoryModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
categoryModalContent: { flex: 1, borderTopLeftRadius: 30, borderTopRightRadius: 30, paddingTop: 20 },
categoryModalHeader: { alignItems: 'center', paddingHorizontal: 20, paddingBottom: 20, borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.1)' },
categoryModalBack: { position: 'absolute', top: 20, left: 20, zIndex: 10, padding: 8 },
categoryModalIcon: { width: 60, height: 60, borderRadius: 30, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
categoryModalTitle: { fontSize: 24, fontWeight: 'bold', marginBottom: 4 },
categoryModalSubtitle: { fontSize: 14 },
categoryModalList: { padding: 20 },
modalCategoryItem: { flexDirection: 'row', alignItems: 'center', padding: 15, borderRadius: 15, borderWidth: 1, marginBottom: 10 },
modalCategoryIcon: { width: 50, height: 50, borderRadius: 25, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
modalCategoryInfo: { flex: 1 },
modalCategoryName: { fontSize: 16, fontWeight: '600', marginBottom: 4 },
modalCategoryRadius: { fontSize: 12 },
loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 40 },
loadingText: { marginTop: 12, fontSize: 14 },
emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 60 },
emptyTitle: { fontSize: 18, fontWeight: '600', marginTop: 16, marginBottom: 8 },
emptyText: { fontSize: 14, textAlign: 'center', paddingHorizontal: 40 },
});