import { Dimensions, StyleSheet } from 'react-native';
export const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    headerArea: { paddingHorizontal: 20, paddingTop: 15, paddingBottom: 5 },
    categoryScroll: { paddingRight: 20, marginBottom: 10, height: 50 },
    categoryPill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 25, marginRight: 10, borderWidth: 1, height: 40 },
    categoryLabel: { marginLeft: 6, fontSize: 13, fontWeight: '800' },
    scrollContent: { paddingHorizontal: 20, paddingBottom: 100 },
    searchWrapper: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, height: 50, borderRadius: 15, borderWidth: 1, marginBottom: 15 },
    searchInput: { flex: 1, marginLeft: 10, fontSize: 15 },
    mapContainer: { width: '100%', height: 250, borderRadius: 30, overflow: 'hidden', marginBottom: 20, borderWidth: 1 },
    map: { width: '100%', height: '100%' },
    customMarker: { padding: 6, borderRadius: 12, borderWidth: 2, borderColor: 'white', elevation: 5 },
    recenterBtn: { position: 'absolute', bottom: 15, right: 15, padding: 10, borderRadius: 12, elevation: 5 },
    resultsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15, paddingHorizontal: 5 },
    sectionTitle: { fontSize: 20, fontWeight: '900' },
    placeCard: { flexDirection: 'row', alignItems: 'center', padding: 10, borderRadius: 22, borderWidth: 1, marginBottom: 12 },
    imgContainer: { width: 75, height: 75, borderRadius: 18, overflow: 'hidden' },
    placeImg: { width: '100%', height: '100%' },
    ratingBadge: { position: 'absolute', top: 5, left: 5, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8 },
    ratingText: { color: 'white', fontSize: 10, fontWeight: '900' },
    placeInfo: { flex: 1, marginLeft: 15 },
    placeName: { fontWeight: '900', fontSize: 16, marginBottom: 4 },
    addressRow: { flexDirection: 'row', alignItems: 'center' },
    placeAddress: { fontSize: 12, opacity: 0.7 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'flex-end' },
    modalContent: { height: height * 0.75, borderTopLeftRadius: 35, borderTopRightRadius: 35, padding: 25, alignItems: 'center' },
    modalHandle: { width: 40, height: 4, backgroundColor: '#444', borderRadius: 2, marginBottom: 20 },
    modalHeroContainer: { width: '100%', height: 280, borderRadius: 25, overflow: 'hidden', marginBottom: 20, position: 'relative' },
    modalHeroImg: { width: '100%', height: '100%' },
    modalBookmarkBtn: { position: 'absolute', top: 15, right: 15, backgroundColor: 'rgba(0,0,0,0.3)', padding: 10, borderRadius: 15 },
    modalTitle: { fontSize: 24, fontWeight: '900', textAlign: 'center' },
    modalSub: { fontSize: 14, textAlign: 'center', marginTop: 8, marginBottom: 30 },
    actionBtn: { width: '100%', height: 60, borderRadius: 20, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
    actionBtnText: { color: 'white', fontWeight: '900', fontSize: 17 },
    closeBtnTop: { position: 'absolute', top: 5, right: 10, zIndex: 10, padding: 8, borderRadius: 20 },
});